sudo: false

language: python

python:
  - "2.7"

cache:
  directories:
    - $HOME/.cache/pip

install:
  - pip install pip wheel codecov virtualenv -U
  - pip install -r requirements-tests.txt

script:
  - coverage run tests.py
  - make bundle

after_success:
  - codecov

branches:
  only:
    - master
